#!/bin/bash

echo -e "\e[00;32mCon este simple script usted borrara todas las anotaciones\e[00m"
echo -e "\e[00;32m@Override de su proyecto\e[00m"
echo -e "\e[00;32mUsted desea continuar [s/n] :\e[00m"
read res




if [ $res == "s" -o $res == "S" ]; then

echo -n -e "\e[00;32mEscriba la ruta donde se encuentra el proyecto :\e[00m"
read ruta

ruta=`echo $ruta | sed -e s/~//g`
ruta=`echo $ruta | sed -e 's,/$,,'`
if [ -z $ruta ]; then
	ruta="src"
	
else
	ruta="$HOME/$ruta/src"

fi

#verifica si el directorio contiene un directorio src
if [ -d $ruta ]; then

	for i in `find $ruta -type f -name "*.java"`; do
	
	permiso=`ls -la $i | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf("%0o ",k);print}' | awk -F ' ' '{print $1}'`
	file=`basename $i`
	cat "$i" | sed -e s/@Override//g > /tmp/$file
	rm -r $i
	mv /tmp/$file $i
	chmod $permiso $i
	done

else 
	
	echo -e "\e[00;32mNo se puede encontrar archivos fuentes, usted podría estar en una ruta incorrecta\e[00m"

fi

else 
	echo -e "\e[00;32mNo se ha realizado nada\e[00m"
	exit
fi




